#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0
rm -f log.* 2>/dev/null
rm -rf sequencedVTK
rm -f domainBoundary.fms
rm -f *.csv

# ----------------------------------------------------------------- end-of-file

