#!/bin/sh

# NOTE: using OpenFOAM's 'runApplication' does not work when submitting
# parameter studies. Thus, its functionality is emulated here using
# echo and output redirection to log files.

# Preprocessing
rm -rf 0 && cp -r 0.org 0 
touch view.foam

echo "Running blockMesh..."
blockMesh > log.blockMesh 2>&1
echo "Running checkMesh..."
checkMesh > log.checkMesh 2>&1

# Create the inlet patch using topoSet and createPatch
echo "Running topoSet..."
topoSet > log.topoSet 2>&1
echo "Running createPatch..."
createPatch -overwrite > log.createPatch 2>&1

# Initialization
echo "Running surfaceInitVolumeFraction..."
surfaceInitVolumeFraction > log.surfaceInitVolumeFraction 2>&1


# Check whether on cluster or on a regular machine

# Submit as cluster job
#if uname -a | grep hpc ; then
#    echo "Submitting job to cluster"
#    ./submit_interFlow.sh
# Run locally
#else
#    cd ${0%/*} || exit 1                        # Run from this directory
#    . $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions
#
#    # Run in serial
#    runApplication -s growingDroplet2D.o interFlow
#fi
#------------------------------------------------------------------------------

